<template>
  <header class="header">
    <img src="~/assets/dalton_logo.png" alt="Dodds Family Smithy Logo" class="header__logo">
    <nav class="header__nav">
      <ul class="nav__list">
        <li class="nav__item"><NuxtLink class="nav__link" to="/">Home</NuxtLink></li>
        <li class="nav__item"><NuxtLink class="nav__link" to="/">Our Story</NuxtLink></li>
        <li class="nav__item"><NuxtLink class="nav__link" to="/shop">Shop</NuxtLink></li>
        <li class="nav__item"><NuxtLink class="nav__link" to="/">Contact</NuxtLink></li>
        <li class="nav__item cart"><NuxtLink class="nav__link" to="/cart">Cart ({{ totalItems }})</NuxtLink></li>
      </ul>
    </nav>
  </header>
</template>
<script>
import { useCartStore } from '@/stores/cartStore'

export default {
  setup() {
    const cartStore = useCartStore()

    return {
      cartStore
    }
  },

  computed: {
    totalItems() {
      return this.cartStore.totalItems
    }  
  }
}
</script>
<style scoped>
.header {
  position: fixed;
  z-index: 999;
  width: 90%;
  height: 85px;
  top: 3%;
  left: 50%;
  transform: translateX(-50%);
  background-color: hsla(0, 0%, 0%, 0.7);
  border-radius: 3px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0 4rem;
  box-sizing: border-box;
}
.header__logo {
  width: 72px;
}

.nav__list {
  display: flex;
  gap: 1.5rem;
}

.nav__link {
  font-family: 'Poppins', sans-serif;
  color: white;
  font-size: 0.95rem;
  text-decoration: none;
  border-bottom: solid 2px transparent;
  transition: border-bottom 0.2s ease-in-out;
  padding-bottom: 2px;
}

.nav__link:hover {
  border-bottom: solid 2px white;
}

.shake {
  animation: shake-horizontal 0.8s ease-in-out;
  animation-iteration-count: infinite;
}

/* ----------------------------------------------
 * Generated by Animista on 2023-3-19 19:53:16
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation shake-horizontal
 * ----------------------------------------
 */
 @-webkit-keyframes shake-horizontal {
  0%,
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
  }
  10%,
  30%,
  50%,
  70% {
    -webkit-transform: translateX(-8px);
            transform: translateX(-8px);
  }
  20%,
  40%,
  60% {
    -webkit-transform: translateX(8px);
            transform: translateX(8px);
  }
  80% {
    -webkit-transform: translateX(6px);
            transform: translateX(6px);
  }
  90% {
    -webkit-transform: translateX(-6px);
            transform: translateX(-6px);
  }
}
@keyframes shake-horizontal {
  0%,
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
  }
  10%,
  30%,
  50%,
  70% {
    -webkit-transform: translateX(-8px);
            transform: translateX(-8px);
  }
  20%,
  40%,
  60% {
    -webkit-transform: translateX(6px);
            transform: translateX(6px);
  }
  80% {
    -webkit-transform: translateX(6px);
            transform: translateX(6px);
  }
  90% {
    -webkit-transform: translateX(-8px);
            transform: translateX(-8px);
  }
}
</style>